### ISSUE TITLE
npm outdated

### ISSUE THREAD

**Issue by ephb** [totev/vodafone-station-cli#165]
First of all, thank you for sharing your work in this repository.

I noticed that the [npm package](https://npm.io/package/vodafone-station-cli) is 2 years old and does not work with current versions of the Vodafone Station as they only answer on `get `and not on `head`, as is already addressed [here](https://github.com/totev/vodafone-station-cli/blob/main/src/modem/discovery.ts).

**Comment by totev** [comment]
Hey @ephb! I'm not familiar with npm.io. How does one publish there? Is it a mirror for npmjs.com?
The publishing is currently wired with the official npm repo: https://www.npmjs.com/package/vodafone-station-cli
Cheers!

**Comment by ephb** [comment]
Oh my mistake entirely, I think I installed trough npm just before your last push or something like that and coincidentally I used a link from npm.io ( which is a package search engine and apparently does not update packages. after indexing them).
I am closing this,

**Comment by totev** [comment]
No worries! Thanks for taking the time to report this!
