### ISSUE TITLE
Arris TG3442DE mit Vodafone West FW

### ISSUE THREAD

**Issue by kennymc-c** [totev/vodafone-station-cli#27]
Wie im Vodafone Forum erwähnt versuche die CLI mit einem Arris TG3442DE im Bridge Modus und der Firmware von Vodafone West (01.04.046.07.EURO.SIP) zu betreiben. Bisher ohne Erfolg:

`vodafone-station-cli docsis
›   Error: Could not fetch docsis status from modem.`

Zum Debugger mal die Ausgabe von `env DEBUG=\* npx vodafone-station-cli docsis`
 
https://pastebin.com/EZiJRCjE

**Comment by totev** [comment]
It seems to fail [here](https://github.com/totev/vodafone-station-cli/blob/d1224bf4c374d0f2e682d17c7d265f67342050b3/src/modem/arris-modem.ts#L164). 
```
      const {data} = await this.httpClient.post<SetPasswordResponse>(
        '/php/ajaxSet_Password.php',
        setPasswordRequest
      )
```
I'm wondering why there's no exception with the modem's response. As my access to an arris is currently limited, I'll work on the log outputs for a better overview of the problem.

**Comment by kennymc-c** [comment]
Any news on this?
Debug Output with 1.2.8:
https://pastebin.com/btCA7QLa
