### ISSUE TITLE
add the output of #/settings/wan | /api/v1/wan and #/status | /api/v1/sta_status 

### ISSUE THREAD

**Issue by MaxPeal** [totev/vodafone-station-cli#66]
please add the output of  #/settings/wan | /api/v1/wan
and 
#/status | /api/v1/sta_status 

as i have connection errors without a degradation of the DOCSIS Status / DOCSIS parameters.

**Comment by MaxPeal** [comment]
how can i collect all the info you need for the new output?

**Comment by totev** [comment]
I'm using mine in bridge mode, so no layer 3 information is available. I'll see what the output is though. @MaxPeal which model do you have?
